"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import Link from "next/link";
import { Users,Swords,Sprout,Mountain,GitBranch,SlidersHorizontal,ChevronRight } from "lucide-react";
import { TemplateProbabilities } from "./TemplateProbabilities";
import { AdminRail } from "@/components/admin/AdminRail";
import { templateProbabilities,templateGrowth,neutralGrowth,attributes,attributeNames,defaultLevelCosts,mutationSchema,type Catalog,type CultivatorMutation } from "@/server/domain/cultivators/config";
import styles from "@/components/resource-management/ResourceManager.module.css";
import ui from "@/components/item-management/ItemManager.module.css";
type Kind=CultivatorMutation["kind"];
type Draft={kind:Kind;value:Record<string,unknown>};
type Workspace=Catalog&{configSet:string;revision:number;sets:{code:string;name:string}[];issues:string[]};
const tabs=[{id:"hero",name:"修士模板",detail:"形象、成长倾向与姓名池",icon:Users},{id:"career",name:"职业成长",detail:"七维、成长与技能",icon:Swords},{id:"route",name:"职业路线",detail:"筑基分支与结丹晋升",icon:GitBranch},{id:"root",name:"灵根资质",detail:"初始与成长倍率",icon:Sprout},{id:"realm",name:"境界配置",detail:"等级范围与突破门槛",icon:Mountain},{id:"rules",name:"培养规则",detail:"升级、突破、还魂与灵息",icon:SlidersHorizontal}] as const;
const zero=()=>Object.fromEntries(attributes.map(a=>[a,0]));
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers}});const b=await r.json();if(!r.ok)throw new Error(b.error?.message??"请求失败");return b;}
export function CultivatorManager({initialConfigSet="v1_0"}:{initialConfigSet?:string}){
 const [data,setData]=useState<Workspace|null>(null),[tab,setTab]=useState<Kind>("hero"),[query,setQuery]=useState(""),[page,setPage]=useState(1),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("正在读取修士配置…"),[error,setError]=useState("");
 const serial=useRef(0);
 const load=useCallback(async(set?:string)=>{const n=++serial.current;const result=await api<Workspace>(`/api/admin/cultivators${set?`?configSet=${encodeURIComponent(set)}`:""}`);if(n===serial.current){setData(result);setPage(1);}return result;},[]);
 useEffect(()=>{load(initialConfigSet).then(()=>setNotice("编辑模板与培养规则，保存后需重新审核发布。")).catch(e=>setNotice(e.message));},[load,initialConfigSet]);
 async function refresh(set?:string,login=false){setBusy(true);try{if(login)await api("/api/admin/resources/local-login",{method:"POST"});await load(set??data?.configSet??initialConfigSet);setNotice("已读取最新配置草稿");}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 function edit(kind:Kind,value?:Record<string,unknown>){const common={code:"",name:"",revision:0,status:"active",sortOrder:0};const defaults:Record<Kind,Record<string,unknown>>={
  hero:{...common,templateClass:"common",acquisitionWeight:0,appearanceCode:"",namePool:[],growthFocus:"",growthModifiers:{...neutralGrowth},careerCode:"",rootCode:"",realmCode:"",initialLevel:1,portraitAssetKey:""},
  career:{...common,tier:0,primaryAttribute:"strength",baseHp:100,base:zero(),growth:zero(),skills:[]},
  root:{...common,basePercent:100,growthPercent:100,rarityOrder:0},
  realm:{...common,orderIndex:data?.realms.length??0,minLevel:1,maxLevel:10,breakthroughLevel:10,breakthroughRecipeCode:null},
  route:{...common,initialCareerCode:"",foundationCareerCode:"",coreCareerCode:"",foundationTrial:"",coreTrial:"",coreBonus:zero()},
  rules:{code:"default",revision:0,maxLevel:30,fixedNames:["","","",""],fixedRoster:Array.from({length:4},(_,i)=>data?.heroes[i]?.code??""),levelCosts:defaultLevelCosts,spiritMax:100,spiritRecoverySeconds:300,foundationStone:300,coreStone:1200,coreDiscount:300,corePillCode:"dustfall_pill",foundationQuest:"four_array_eyes",coreQuest:"map_03_main",discountQuest:"borrow_array",foundationResetStone:3000,coreResetStone:9000,revive:[{realmCode:"lian_qi",base:20,perLevel:8,offset:0},{realmCode:"zhu_ji",base:100,perLevel:15,offset:10},{realmCode:"jie_dan",base:300,perLevel:25,offset:20}]},
 };setDraft({kind,value:value??defaults[kind]});setError("");}
 async function save(){if(!data||!draft)return;const p=mutationSchema.safeParse(draft);if(!p.success){setError(p.error.issues.map(i=>`${i.path.slice(1).join(".")}：${i.message}`).join("\n"));return;}setBusy(true);try{await api("/api/admin/cultivators",{method:"POST",body:JSON.stringify({configSet:data.configSet,mutation:p.data})});setDraft(null);setNotice("草稿已保存，请重新校验和审核。");try{await load(data.configSet);}catch{setNotice("保存成功，刷新失败，请手动刷新。");}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const collection=data?(tab==="hero"?data.heroes:tab==="career"?data.careers:tab==="root"?data.roots:tab==="realm"?data.realms:tab==="route"?data.routes:[]):[];
 const rows=collection.filter(r=>`${r.code} ${r.name} ${"appearanceCode" in r?r.appearanceCode:""}`.toLowerCase().includes(query.toLowerCase())),pages=Math.max(1,Math.ceil(rows.length/15)),current=Math.min(page,pages);
 function detail(row:typeof rows[number]){if("careerCode" in row)return `${data?.careers.find(c=>c.code===row.careerCode)?.name??row.careerCode} · ${row.templateClass==="common"?"普通":"优秀"} · 默认渠道 ${((templateProbabilities(data?.heroes??[],row.careerCode).find(p=>p.code===row.code)?.probability??0)*100).toFixed(2)}% · ${row.appearanceCode} · ${row.growthFocus||"标准成长"}`;if("basePercent" in row)return `初始 ${row.basePercent}% · 成长 ${row.growthPercent}%`;if("minLevel" in row)return `Lv${row.minLevel}–${row.maxLevel}`;if("tier" in row)return `${["炼气","筑基","结丹"][row.tier]} · ${row.skills.length}/3 技能`;return `${row.initialCareerCode} → ${row.foundationCareerCode} → ${row.coreCareerCode}`;}
 return <div className={styles.shell}><header className="app-header"><div className="brand-lockup"><div className="brand-seal">昆</div><div><strong>昆吾司典</strong><span>KUNWU CONFIG CONSOLE</span></div></div><div className="header-context"><span>修士管理</span><i/><strong>名册与成长</strong></div><div className="header-actions"><span className="status-badge">{data?`草稿修订 ${data.revision}`:"等待连接"}</span></div></header>
 <div className={styles.workspace}><AdminRail configSet={data?.configSet??initialConfigSet}/><aside className="config-sidebar"><div className="sidebar-heading"><div><span className="section-kicker">CULTIVATOR MANAGEMENT</span><h2>修士管理</h2></div><Users size={18}/></div><p className="config-sidebar__hint">修士模板与成长规则<br/>灵根、境界与物品品级各自独立。</p><nav className="config-module-list" aria-label="修士管理功能">{tabs.map(t=><button key={t.id} className={tab===t.id?"is-active":""} aria-current={tab===t.id?"page":undefined} onClick={()=>{setTab(t.id);setQuery("");setPage(1);}}><t.icon size={20}/><span><strong>{t.name}</strong><small>{t.detail}</small></span><ChevronRight size={14}/></button>)}</nav></aside>
 <main className={styles.root}><div className={styles.content}><header><div><span className="section-kicker">KUNWU CULTIVATOR CONSOLE</span><h1>{tabs.find(t=>t.id===tab)?.name}</h1><p>{tabs.find(t=>t.id===tab)?.detail}</p></div><Users size={28}/></header><p role="status" className={styles.notice}>{notice}</p>
 {!data?<section><h2>连接管理身份</h2><p>使用本机开发会话管理配置草稿。</p><button disabled={busy} onClick={()=>refresh(undefined,true)}>连接本机开发身份</button></section>:<>
 <div className={ui.toolbar}><label>配置集<select value={data.configSet} disabled={busy} onChange={e=>refresh(e.target.value)}>{data.sets.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><button disabled={busy} onClick={()=>refresh()}>刷新</button><button disabled={busy} onClick={()=>refresh(undefined,true)}>重连身份</button><Link href={`/config?configSet=${data.configSet}`}>审核与发布 →</Link></div>
 {data.issues.length>0&&<details><summary>发布前还需完善 {data.issues.length} 项配置</summary>{data.issues.map(i=><p key={i}>{i}</p>)}</details>}
 {tab==="hero"&&<TemplateProbabilities key={`${data.configSet}:${data.revision}`} data={data} onSaved={async()=>{await load(data.configSet);setNotice("模板概率草稿已保存，请重新审核发布。");}}/>}
 {tab!=="rules"?<section><div className={ui.toolbar}><input aria-label="搜索修士配置" placeholder="搜索模板、形象或编码" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><button disabled={busy} onClick={()=>edit(tab)}>新增{tabs.find(t=>t.id===tab)?.name}</button></div><div className={styles.scroll}><table><thead><tr><th>{tab==="hero"?"形象模板 / 编码":"名称 / 编码"}</th><th>配置摘要</th><th>状态</th><th>修订</th><th>操作</th></tr></thead><tbody>{rows.slice((current-1)*15,current*15).map(row=><tr key={row.code}><td>{row.name}<code className={ui.code}>{row.code}</code></td><td>{detail(row)}</td><td>{row.status==="active"?"启用":"停用"}</td><td>{row.revision}</td><td><button disabled={busy} onClick={()=>edit(tab,row)}>编辑</button></td></tr>)}</tbody></table></div>{!rows.length&&<p className={ui.empty}>{query?"没有匹配的配置":"尚无配置，点击新增开始维护。"}</p>}<div className={ui.toolbar}><button disabled={current===1} onClick={()=>setPage(current-1)}>上一页</button><span>{current} / {pages} 页 · {rows.length} 条</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>下一页</button></div></section>:<section><div className={styles.panelHeading}><h2>培养规则</h2><button disabled={busy} onClick={()=>edit("rules",data.rules??undefined)}>{data.rules?"编辑规则":"配置规则"}</button></div>{data.rules?<><p>固定 {data.rules.fixedRoster.length} 人 · 等级上限 {data.rules.maxLevel} · 1→30 级累计魂晶 {data.rules.levelCosts.reduce((a,b)=>a+b,0)}</p><p>筑基灵石 {data.rules.foundationStone} · 结丹灵石 {data.rules.coreStone} · 支线优惠 {data.rules.coreDiscount}</p><p>灵息上限 {data.rules.spiritMax} · 营地每 {data.rules.spiritRecoverySeconds} 秒恢复 1 点</p><details><summary>逐级魂晶与还魂规则</summary><div className={styles.scroll}><table><thead><tr><th>目标等级</th><th>魂晶</th></tr></thead><tbody>{data.rules.levelCosts.map((c,i)=><tr key={i}><td>{i+2}</td><td>{c}</td></tr>)}</tbody></table></div>{data.rules.revive.map(r=><p key={r.realmCode}>{r.realmCode}：{r.base} + {r.perLevel} ×（等级 − {r.offset}），向上取整到 5 的倍数</p>)}</details></>:<p>设置四名初始修士、逐级魂晶、突破费用及还魂规则。</p>}<p>当前为配置阶段；保存不改变已有玩家的等级和成长。</p></section>}
 </> }</div>{draft&&data&&<Editor data={data} draft={draft} busy={busy} error={error} change={setDraft} close={()=>setDraft(null)} save={save}/>}</main></div><footer className={styles.footer}><span>昆吾司典 · 修士配置</span><span>development · 配置草稿</span></footer></div>;
}
function Editor({data,draft,busy,error,change,close,save}:{data:Workspace;draft:Draft;busy:boolean;error:string;change:(d:Draft)=>void;close:()=>void;save:()=>void}){
 const panel=useRef<HTMLDivElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement|null;panel.current?.focus();return()=>old?.focus();},[]);
 const v=draft.value,k=draft.kind;
 const set=(key:string,value:unknown)=>change({...draft,value:{...v,[key]:value}});
 const input=(key:string,label:string,type="text",nullable=false,disabled=false)=><label>{label}<input disabled={disabled} type={type} value={String(v[key]??"")} onChange={e=>set(key,e.target.value===""?(nullable?null:""):type==="number"?Number(e.target.value):e.target.value)}/></label>;
 const select=(key:string,label:string,options:{code:string;name:string}[])=><label>{label}<select value={String(v[key]??"")} onChange={e=>set(key,e.target.value)}><option value="">请选择</option>{options.map(o=><option key={o.code} value={o.code}>{o.name} · {o.code}</option>)}</select></label>;
 const stats=(key:string,title:string)=><fieldset><legend>{title}</legend><div className={styles.form}>{attributes.map(a=><label key={a}>{attributeNames[a]}<input type="number" min={0} value={String((v[key] as Record<string,number>)[a])} onChange={e=>set(key,{...(v[key] as object),[a]:Number(e.target.value)})}/></label>)}</div></fieldset>;
 const selectedCareer=data.careers.find(c=>c.code===v.careerCode);
 const selectedRoot=data.roots.find(r=>r.code===v.rootCode);
 const slots=(v.skills??[]) as {code:string;unlockLevel:number;auto:boolean}[];
 return <div className={ui.overlay}><div ref={panel} className={ui.drawer} role="dialog" aria-modal="true" aria-label="编辑修士配置" tabIndex={-1} onKeyDown={e=>{if(e.key==="Escape"&&!busy)close();if(e.key==="Tab"){const els=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className={styles.panelHeading}><h2>{tabs.find(t=>t.id===k)?.name}</h2><button disabled={busy} onClick={close}>关闭</button></div>
 <form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={busy} className={styles.flatFieldset}>
 {k!=="rules"&&<div className={styles.form}>{input("name",k==="hero"?"模板名称（如金刚禅修）":"名称")}{input("code","稳定编码","text",false,Number(v.revision)>0)}{select("status","状态",[{code:"active",name:"启用"},{code:"disabled",name:"停用"}])}{input("sortOrder","排序","number")}</div>}
 {k==="hero"&&<><div className={styles.form}>{select("careerCode","初始职业",data.careers)}{select("rootCode","灵根",data.roots)}{select("realmCode","初始境界",data.realms)}{input("initialLevel","初始等级","number")}</div>{select("templateClass","模板分类",[{code:"common",name:"普通"},{code:"excellent",name:"优秀"}])}<p>获取概率请在模板列表上方的“模板获取概率”中统一配置，同职业合计100%。新增模板默认不参与获取。</p>{input("appearanceCode","形象编码")}{input("portraitAssetKey","头像资源路径（可选）")}{input("growthFocus","成长倾向（如力道中上、肉身最高）")}<label>随机姓名池（每行一个）<textarea rows={5} value={(v.namePool as string[]).join("\n")} onChange={e=>set("namePool",e.target.value.split("\n"))}/></label>{stats("growthModifiers","模板成长倍率（千分位，1000 = 职业成长 ×1）")}{selectedCareer&&<p>每级成长预览：{attributes.map(a=>`${attributeNames[a]} ${templateGrowth(selectedCareer.growth[a],(v.growthModifiers as Record<string,number>)[a],selectedRoot?.growthPercent??100).toFixed(3)}`).join(" · ")}</p>}<p>实际成长 = 当前职业成长 × 模板倍率 × 灵根倍率。同职业可有多个形象与成长模板；姓名在创建修士时独立选取并固定。</p><p>成长与权重为配置草稿。治疗、抗性、嘲讽和攻击频率须接入实际技能及战斗逻辑，当前不会仅凭模板定位生效。</p><p>模板变更用于新实例；不重算已有修士。</p></>}
 {k==="root"&&<div className={styles.form}>{input("basePercent","初始倍率 %","number")}{input("growthPercent","成长倍率 %","number")}{input("rarityOrder","资质顺序","number")}</div>}
 {k==="realm"&&<><div className={styles.form}>{input("orderIndex","境界顺序","number")}{input("minLevel","最低等级","number")}{input("maxLevel","最高等级","number")}{input("breakthroughLevel","突破等级（末境界留空）","number",true)}</div><details><summary>兼容字段</summary>{input("breakthroughRecipeCode","旧突破配方编码（可选）","text",true)}</details></>}
 {k==="career"&&<><div className={styles.form}><label>职业阶段<select value={Number(v.tier)} onChange={e=>set("tier",Number(e.target.value))}><option value={0}>炼气</option><option value={1}>筑基</option><option value={2}>结丹</option></select></label>{select("primaryAttribute","主属性",attributes.map(a=>({code:a,name:attributeNames[a]})))}{input("baseHp","基础生命","number")}</div>{stats("base","Lv1 基础七维")}{stats("growth","每级成长（千分位，1000 = 1点）")}<fieldset><legend>三个阶段技能</legend>{slots.map((slot,i)=><div key={i} className={styles.form}><label>技能 {i+1}<select value={slot.code} onChange={e=>set("skills",slots.map((s,n)=>n===i?{...s,code:e.target.value}:s))}><option value="">请选择</option>{data.skills.map(s=><option key={s.code} value={s.code}>{s.name} · {s.code}</option>)}</select></label><label>解锁等级<input type="number" min={1} value={slot.unlockLevel} onChange={e=>set("skills",slots.map((s,n)=>n===i?{...s,unlockLevel:Number(e.target.value)}:s))}/></label><label><input type="checkbox" checked={slot.auto} onChange={e=>set("skills",slots.map((s,n)=>n===i?{...s,auto:e.target.checked}:s))}/>默认自动施放</label><button type="button" onClick={()=>set("skills",slots.filter((_,n)=>n!==i))}>移除</button></div>)}<button type="button" disabled={slots.length>=3} onClick={()=>set("skills",[...slots,{code:"",unlockLevel:1,auto:true}])}>添加技能槽</button><p>允许先保存未完成草稿，发布时校验三个技能及所有引用。</p></fieldset></>}
 {k==="route"&&<><div className={styles.form}>{select("initialCareerCode","初始职业",data.careers.filter(c=>c.tier===0))}{select("foundationCareerCode","筑基分支",data.careers.filter(c=>c.tier===1))}{select("coreCareerCode","结丹晋升",data.careers.filter(c=>c.tier===2))}{input("foundationTrial","筑基试炼编码")}{input("coreTrial","结丹试炼编码")}</div>{stats("coreBonus","结丹一次性七维增量")}</>}
 {k==="rules"&&<><p>固定四人 · 炼气1–10 / 筑基11–20 / 结丹21–30</p><fieldset><legend>初始队伍</legend><div className={styles.form}>{(v.fixedRoster as string[]).map((h,i)=><label key={i}>位置 {i+1}<select value={h} onChange={e=>set("fixedRoster",(v.fixedRoster as string[]).map((s,n)=>n===i?e.target.value:s))}><option value="">请选择模板</option>{data.heroes.map(h=><option key={h.code} value={h.code}>{h.name}</option>)}</select>固定姓名（留空从姓名池随机）<input value={(v.fixedNames as string[])[i]} onChange={e=>set("fixedNames",(v.fixedNames as string[]).map((s,n)=>n===i?e.target.value:s))}/></label>)}</div></fieldset>
 <fieldset><legend>升级魂晶（按目标等级）</legend><div className={styles.form}>{(v.levelCosts as number[]).map((cost,i)=><label key={i}>升至 Lv{i+2}<input type="number" min={1} value={cost} onChange={e=>set("levelCosts",(v.levelCosts as number[]).map((c,n)=>n===i?Number(e.target.value):c))}/></label>)}</div></fieldset>
 <fieldset><legend>突破与专精重置</legend><div className={styles.form}>{input("foundationStone","筑基灵石","number")}{input("coreStone","结丹基础灵石","number")}{input("coreDiscount","借阵结丹优惠","number")}{input("corePillCode","结丹丹药编码（固定消耗1个）")}{input("foundationResetStone","筑基重置灵石","number")}{input("coreResetStone","结丹重置灵石","number")}{input("foundationQuest","筑基主线条件编码")}{input("coreQuest","结丹主线条件编码")}{input("discountQuest","优惠支线编码")}</div><p>跨级魂晶取上方11级和21级费用，突破时两种费用分栏结算。</p></fieldset>
 <fieldset><legend>灵息恢复</legend><div className={styles.form}>{input("spiritMax","灵息上限","number")}{input("spiritRecoverySeconds","营地恢复1点所需秒数","number")}</div></fieldset>
 <fieldset><legend>还魂费用</legend><p>基础费用 + 每级费用 ×（当前等级 − 起算等级），向上取整到5的倍数。</p>{(v.revive as {realmCode:string;base:number;perLevel:number;offset:number}[]).map((r,i)=><div key={i} className={styles.form}><label>境界<select value={r.realmCode} onChange={e=>set("revive",(v.revive as typeof r[]).map((x,n)=>n===i?{...x,realmCode:e.target.value}:x))}>{data.realms.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label>{([['base','基础费用'],['perLevel','每级费用'],['offset','起算等级']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={r[key]} onChange={e=>set("revive",(v.revive as typeof r[]).map((x,n)=>n===i?{...x,[key]:Number(e.target.value)}:x))}/></label>)}</div>)}</fieldset></>}
 </fieldset>{error&&<p className={ui.error} role="alert">{error}</p>}<div className={styles.actions}><button disabled={busy} type="button" onClick={close}>取消</button><button disabled={busy} type="submit">{busy?"保存中…":"保存草稿"}</button></div></form></div></div>;
}
