"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import { MarketConfig } from "./MarketConfig";
import Link from "next/link";
import { Package, Gem, Hammer, Store, ChevronRight, Plus } from "lucide-react";
import { AdminRail } from "@/components/admin/AdminRail";
import { categories, categoryNames, mutationSchema, type Catalog, type ItemMutation, type CraftCost } from "@/server/domain/items/config";
import styles from "@/components/resource-management/ResourceManager.module.css";
import ui from "./ItemManager.module.css";
type Workspace=Catalog&{sets:{code:string;name:string}[];configSet:string;revision:number;workshopRevision:number};
type Kind=ItemMutation["kind"];
type Draft={kind:Kind;value:Record<string,unknown>};
const tabs=[{id:"item",name:"物品目录",detail:"分类、品级与存储规则",icon:Package},{id:"quality",name:"品级管理",detail:"六个等级与展示颜色",icon:Gem},{id:"recipe",name:"炼制配方",detail:"炼器坊等级与材料消耗",icon:Hammer},{id:"market",name:"交易行",detail:"系统商品、库存与刷新",icon:Store}];
const defaultCosts=[40,60,90,130,180,240,320,420,540,680,850,1050,1280,1540,1840,2180,2560,2980,3440,3940,4500,5120,5800];
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers}});const b=await r.json();if(!r.ok)throw new Error(b.error?.message??"请求失败");return b;}
export function ItemManager({initialConfigSet="v1_0",initialTab="item"}:{initialConfigSet?:string;initialTab?:string}){
  const [data,setData]=useState<Workspace|null>(null),[tab,setTab]=useState(tabs.some(t=>t.id===initialTab)?initialTab:"item"),[query,setQuery]=useState(""),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("正在连接…"),[error,setError]=useState("");
  const [statusFilter,setStatusFilter]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[qualityFilter,setQualityFilter]=useState(""),[page,setPage]=useState(1);
  const sequence=useRef(0);
  const load=useCallback(async(set?:string)=>{const seq=++sequence.current;const result=await api<Workspace>(`/api/admin/items${set?`?configSet=${encodeURIComponent(set)}`:""}`);if(seq===sequence.current){setData(result);setPage(1);}return result;},[]);
  useEffect(()=>{load(initialConfigSet).then(()=>setNotice("配置保存后，需在版本与发布中校验、审核并发布。")).catch(e=>setNotice(e.message));},[load,initialConfigSet]);
  async function login(){setBusy(true);try{await api("/api/admin/resources/local-login",{method:"POST"});await load(data?.configSet??initialConfigSet);setNotice("已连接开发管理身份");}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function reload(set?:string){setBusy(true);try{await load(set??data?.configSet);setNotice("已刷新配置");}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  function edit(kind:Kind,value?:Record<string,unknown>){setError("");const common={code:"",name:"",revision:0,status:"active",sortOrder:0};setDraft({kind,value:value??(kind==="item"?{...common,category:"material",usageTag:"material",qualityCode:null,stackLimit:9999,iconPath:"",isMarketSellable:false,isProtected:false,isDiscardable:true}:kind==="scheme"?{...common,category:"processed",usageTag:"ingot"}:kind==="quality"?{...common,schemeCode:"unified",color:"#B8BCB7"}:kind==="recipe"?{...common,availability:"planned",workshopLevel:1,outputCode:"",outputQuantity:1,costs:[{kind:"resource",code:"darkIron",quantity:8}]}:{revision:data?.workshopRevision??0,woodCode:"spiritWood",costs:defaultCosts})});}
  async function save(){if(!draft||!data)return;const parsed=mutationSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues.map(i=>`${i.path.slice(1).join(".")}：${i.message}`).join("\n"));return;}setBusy(true);try{await api("/api/admin/items",{method:"POST",body:JSON.stringify({configSet:data.configSet,mutation:parsed.data})});setDraft(null);setNotice("已保存草稿，当前审核已失效，请重新校验和审核。");try{await load(data.configSet);}catch{setNotice("已保存，但刷新失败，请点击刷新查看最新修订。");}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const isItemTab=tab==="item";
  const rows=data?(isItemTab?data.items:tab==="quality"?data.qualities:data.recipes).filter(r=>`${r.name} ${r.code}`.toLowerCase().includes(query.toLowerCase())&&(!statusFilter||r.status===statusFilter)&&(!categoryFilter||!("category" in r)||r.category===categoryFilter)&&(!qualityFilter||!("qualityCode" in r)||r.qualityCode===qualityFilter)):[];
  const pageCount=Math.max(1,Math.ceil(rows.length/20)),currentPage=Math.min(page,pageCount);
  return <div className={styles.shell}>
    <header className="app-header"><div className="brand-lockup"><div className="brand-seal">昆</div><div><strong>昆吾司典</strong><span>KUNWU CONFIG CONSOLE</span></div></div><div className="header-context"><span>物品管理</span><i/><strong>百宝录 · 炼器坊 · 交易行</strong></div><div className="header-actions"><span className="status-badge">{data?`草稿修订 ${data.revision}`:"等待连接"}</span></div></header>
    <div className={styles.workspace}><AdminRail configSet={data?.configSet??initialConfigSet}/><aside className="config-sidebar"><div className="sidebar-heading"><div><span className="section-kicker">ITEM MANAGEMENT</span><h2>物品管理</h2></div><Package size={18}/></div><p className="config-sidebar__hint">物品、品级、炼制与交易<br/>统一配置，审核后发布。</p><nav className="config-module-list" aria-label="物品管理功能">{tabs.map(t=><button key={t.id} className={tab===t.id?"is-active":""} aria-current={tab===t.id?"page":undefined} onClick={()=>{setTab(t.id);setQuery("");setPage(1);setStatusFilter("");setCategoryFilter("");setQualityFilter("");}}><t.icon size={20}/><span><strong>{t.name}</strong><small>{t.detail}</small></span><ChevronRight size={14}/></button>)}<Link href={`/items/equipment?configSet=${data?.configSet??initialConfigSet}`}><Package size={20}/><span><strong>装备模板</strong><small>属性预算与生成规则</small></span><ChevronRight size={14}/></Link></nav></aside>
    <main className={styles.root}><div className={styles.content}><header><div><span className="section-kicker">KUNWU ITEM CATALOG</span><h1>{tabs.find(t=>t.id===tab)?.name}</h1><p>{tabs.find(t=>t.id===tab)?.detail}</p></div><Package size={28}/></header><p className={styles.notice} role="status">{notice}</p>
    {!data?<section><h2>连接管理身份</h2><p>使用本机开发会话管理配置草稿。</p><button disabled={busy} onClick={login}>连接本机开发身份</button></section>:<>
    <div className={ui.toolbar}><label>配置集<select aria-label="配置集" value={data.configSet} disabled={busy} onChange={e=>reload(e.target.value)}>{data.sets.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><button disabled={busy} onClick={()=>reload()}>刷新</button><Link href={`/config?configSet=${data.configSet}`}>前往版本与发布 →</Link></div>
    {tab==="market"&&<MarketConfig key={`${data.configSet}:${data.market?.revision??0}`} data={data} onSaved={async()=>{await load(data.configSet);setNotice("系统商店配置已保存，需审核发布。");}}/>}
    {tab==="item"&&<section><p>共 {data.items.length} 条物品资料 · 已绑定图片 {data.items.filter(i=>i.iconPath).length} 条 · 待配图 {data.items.filter(i=>!i.iconPath).length} 条。装备及高阶突破物中的待定资料保持停用，详情保留原始来源与设定。</p></section>}
    {tab==="quality"&&<section><h2>统一六档品级</h2><p>法器 → 真宝 → 法宝 → 古宝 → 通天灵宝 → 玄天之宝</p><p>所有物品共用此顺序。等级名称和顺序固定，可调整展示颜色。</p></section>}
    {tab==="recipe"&&<section><div className={styles.panelHeading}><h2>炼器坊</h2><button onClick={()=>edit("workshop",data.workshop??undefined)}>配置升级消耗</button></div><p>{data.workshop?`初始 1 级 · 最高 24 级 · 全部升级共消耗 ${data.workshop.costs.reduce((a,b)=>a+b,0)} 灵木`:"尚未配置 1–24 级升级消耗。先配置炼器坊，再启用配方。"}</p><p>首期配方即时炼制、固定产出。涉及灵石或随机产出的配方暂不启用。</p></section>}
    {tab!=="market"&&<section><div className={ui.toolbar}><input aria-label="搜索物品或配方" placeholder="搜索名称或编码" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><select aria-label="筛选状态" value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1);}}><option value="">全部状态</option><option value="active">启用</option><option value="disabled">停用</option></select>{isItemTab&&<><select aria-label="筛选分类" value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);setPage(1);}}><option value="">全部分类</option>{categories.map(c=><option key={c} value={c}>{categoryNames[c]}</option>)}</select><select aria-label="筛选品级" value={qualityFilter} onChange={e=>{setQualityFilter(e.target.value);setPage(1);}}><option value="">全部品级</option>{data.qualities.map(q=><option key={q.code} value={q.code}>{q.name}</option>)}</select></>}{(tab==="item"||tab==="recipe")&&<button onClick={()=>edit(tab as Kind)}><Plus size={13}/> 新增{tab==="item"?"物品":"配方"}</button>}</div>
      <div className={styles.scroll}><table><thead><tr><th>名称 / 编码</th><th>{isItemTab?"分类 / 品级":tab==="quality"?"等级":"炼器坊 / 产物"}</th>{isItemTab&&<th>图片 / 内容状态</th>}<th>状态</th><th>修订</th><th>操作</th></tr></thead><tbody>{rows.slice((currentPage-1)*20,currentPage*20).map(row=><tr key={row.code}><td>{"color" in row&&<span className={ui.swatch} style={{background:row.color}}/>}{row.name}<code className={ui.code}>{row.code}</code></td><td>{"category" in row?`${categoryNames[row.category]} · ${data.qualities.find(q=>q.code===row.qualityCode)?.name??"无品级"}`:"schemeCode" in row?`第 ${row.sortOrder+1} 级`:"workshopLevel" in row?row.outcomes.length?`${row.workshopLevel} 级 · ${row.outcomes.length} 种随机结果`:`${row.workshopLevel} 级 · ${row.outputCode} × ${row.outputQuantity}`:""}</td>{isItemTab&&"details" in row&&<td>{row.iconPath.startsWith("/items/")?<Image src={row.iconPath} alt={row.name} width={40} height={40} unoptimized/>:<span>待配图</span>}<small className={ui.code}>{row.details.contentStatus==="ready"?"资料齐备":"数值/映射待完善"}</small></td>}<td>{row.status==="disabled"?"已停用":"availability" in row&&row.availability==="planned"?"待定":"已启用"}</td><td>{row.revision}</td><td><button onClick={()=>edit(tab as Kind,row)}>编辑</button></td></tr>)}</tbody></table></div><div className={styles.actions}><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>上一页</button><span>第 {currentPage} / {pageCount} 页 · {rows.length} 条</span><button disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>下一页</button></div>{!rows.length&&<div className={ui.empty}><Package size={28}/><p>{query||statusFilter||categoryFilter||qualityFilter?"没有匹配的记录":tab==="market"?"暂无物品，请先在物品目录新增。":"暂无配置，点击新增开始管理。"}</p></div>}</section>}</>}
    </div>{draft&&data&&<Editor draft={draft} data={data} busy={busy} error={error} setDraft={setDraft} close={()=>setDraft(null)} save={save}/>}</main></div><footer className={styles.footer}><span>昆吾司典 · 物品配置</span><span>development · 保存草稿 / 审核发布</span></footer>
  </div>;
}
function Editor({draft,data,busy,error,setDraft,close,save}:{draft:Draft;data:Workspace;busy:boolean;error:string;setDraft:(d:Draft)=>void;close:()=>void;save:()=>void}){
  const panel=useRef<HTMLDivElement>(null);
  useEffect(()=>{const old=document.activeElement as HTMLElement|null;panel.current?.focus();return()=>old?.focus();},[]);
  const v=draft.value,kind=draft.kind;
  const update=(key:string,value:unknown)=>setDraft({...draft,value:{...v,[key]:value,...((key==="isProtected"&&value===true)||(key==="category"&&value==="quest")?{isMarketSellable:false}:{})}});
  const field=(key:string,label:string,type="text",disabled=false)=><label>{label}<input required={key!=="iconPath"} type={type} disabled={disabled} value={String(v[key]??"")} min={type==="number"?0:undefined} onChange={e=>update(key,type==="number"?(e.target.value===""?"":Number(e.target.value)):e.target.value)}/></label>;
  const select=(key:string,label:string,options:{code:string;name:string}[],nullable=false)=><label>{label}<select disabled={kind==="quality"&&key==="status"} value={String(v[key]??"")} onChange={e=>update(key,nullable?(e.target.value||null):e.target.value)}><option value="">{nullable?"无品级":"请选择"}</option>{options.map(o=><option key={o.code} value={o.code}>{o.name} · {o.code}</option>)}</select></label>;
  const costs=(v.costs??[]) as CraftCost[];
  return <div className={ui.overlay}><div className={ui.drawer} role="dialog" aria-modal="true" aria-label="编辑配置" tabIndex={-1} ref={panel} onKeyDown={e=>{if(e.key==="Escape"&&!busy)close();if(e.key==="Tab"){const all=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}>
    <div className={styles.panelHeading}><h2>{kind==="workshop"?"炼器坊等级":Number(v.revision)>0?"编辑配置":"新增配置"}</h2><button disabled={busy} onClick={close}>关闭</button></div><form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={busy} className={styles.flatFieldset}>
    {kind!=="workshop"&&<div className={styles.form}>{field("name","名称","text",kind==="quality")}{field("code","稳定编码","text",Number(v.revision)>0)}{select("status","状态",[{code:"active",name:"启用"},{code:"disabled",name:"停用"}])}{field("sortOrder","排序","number",kind==="quality")}</div>}
    {(kind==="item"||kind==="scheme")&&<div className={styles.form}>{select("category","分类",categories.map(c=>({code:c,name:categoryNames[c]})))}{field("usageTag","用途标识（如 ingot）")}</div>}
    {kind==="item"&&<><div className={styles.form}>{select("qualityCode","品级",data.qualities.filter(q=>q.status==="active"&&data.schemes.some(s=>s.code===q.schemeCode&&s.status==="active"&&s.code==="unified")).map(q=>({code:q.code,name:q.name})),true)}{field("stackLimit","堆叠上限","number")}</div>{field("iconPath","图标路径（可选）")}<div className={styles.actions}>{["isProtected","isDiscardable"].map((k,i)=><label key={k}><input type="checkbox" checked={Boolean(v[k])} onChange={e=>update(k,e.target.checked)}/>{i===0?"保护物品":"允许丢弃"}</label>)}</div><fieldset><legend>物品资料</legend><p>系统商品价格、库存与启用状态在“交易行”中配置。</p>{["source","description","usageScope"].map(key=><label key={key}>{{source:"资料来源",description:"用途与设定",usageScope:"使用场景"}[key]}<textarea rows={key==="description"?5:2} value={String((v.details as Record<string,unknown>??{})[key]??"")} onChange={e=>update("details",{...(v.details as object??{}),[key]:e.target.value})}/></label>)}<div className={styles.form}>{["weight","holdLimit","resourceYield"].map(key=><label key={key}>{{weight:"负重（未定留空）",holdLimit:"账号持有上限（非堆叠上限）",resourceYield:"使用获得资源数量"}[key]}<input type="number" value={String((v.details as Record<string,unknown>??{})[key]??"")} onChange={e=>update("details",{...(v.details as object??{}),[key]:e.target.value===""?null:Number(e.target.value)})}/></label>)}</div><p>资源编码：{String((v.details as Record<string,unknown>??{}).resourceCode??"无")} · 包装档位：{String((v.details as Record<string,unknown>??{}).packTier??"无")}</p></fieldset></>}
    {kind==="quality"&&<div className={styles.form}>{field("color","展示颜色","color")}</div>}
    {kind==="recipe"&&<>{Array.isArray(v.outcomes)&&v.outcomes.length>0&&<p>随机产出：{(v.outcomes as {code:string;quantity:number;weight:number}[]).map(o=>`${data.items.find(i=>i.code===o.code)?.name??o.code} ×${o.quantity}（权重${o.weight}）`).join("；")}。产出物品字段仅保留兼容引用，实际按结果池抽取；执行器接入前保持待定。</p>}<div className={styles.form}>{select("availability","配方状态",[{code:"planned",name:"待定（不发布）"},{code:"ready",name:"就绪"}])}{field("workshopLevel","炼器坊等级","number")}{select("outputCode","产出物品",data.items.map(i=>({code:i.code,name:i.name})))}{field("outputQuantity","产出数量","number")}</div><h3>材料消耗</h3>{costs.map((cost,i)=><div className={ui.cost} key={i}><select aria-label={`材料 ${i+1} 类型`} value={cost.kind} onChange={e=>update("costs",costs.map((c,n)=>n===i?{...c,kind:e.target.value,code:""}:c))}><option value="resource">资源</option><option value="item">物品</option><option value="currency">货币</option></select><input aria-label={`材料 ${i+1} 编码`} list="cost-assets" placeholder="材料编码" value={cost.code} onChange={e=>update("costs",costs.map((c,n)=>n===i?{...c,code:e.target.value}:c))}/><input aria-label={`材料 ${i+1} 数量`} type="number" min={1} value={cost.quantity} onChange={e=>update("costs",costs.map((c,n)=>n===i?{...c,quantity:Number(e.target.value)}:c))}/><button type="button" onClick={()=>update("costs",costs.filter((_,n)=>n!==i))}>移除</button></div>)}<datalist id="cost-assets">{data.assets.filter(a=>a.status==="active").map(a=><option key={a.code} value={a.code}/>)}</datalist><button type="button" onClick={()=>update("costs",[...costs,{kind:"item",code:"",quantity:1}])}>添加材料</button></>}
    {kind==="workshop"&&<><p>初始 1 级，最高 24 级；仅消耗灵木。</p><div className={styles.form}>{(v.costs as number[]).map((cost,i)=><label key={i}>升至 {i+2} 级<input type="number" min={1} required value={cost} onChange={e=>update("costs",(v.costs as number[]).map((c,n)=>n===i?Number(e.target.value):c))}/></label>)}</div></>}
    </fieldset>{error&&<p role="alert" className={ui.error}>{error}</p>}<div className={styles.actions}><button type="button" disabled={busy} onClick={close}>取消</button><button type="submit" disabled={busy}>{busy?"保存中…":"保存草稿"}</button></div></form>
  </div></div>;
}
