"use client";
import { useState } from "react";
import { marketSchema } from "@/server/domain/items/market";
import type { Catalog } from "@/server/domain/items/config";
import styles from "@/components/resource-management/ResourceManager.module.css";
import ui from "./ItemManager.module.css";
export function MarketConfig({data,onSaved}:{data:Catalog&{configSet:string};onSaved:()=>Promise<unknown>}){
 const [draft,setDraft]=useState(data.market),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 if(!draft)return <section><h2>系统商店</h2><p>当前配置集尚未配置系统商店商品。</p></section>;
 const value=draft;
 async function save(){const parsed=marketSchema.safeParse(value);if(!parsed.success){setNotice(parsed.error.issues.map(i=>i.message).join("；"));return;}setBusy(true);try{
  const r=await fetch("/api/admin/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({configSet:data.configSet,mutation:{kind:"market",value:parsed.data}})});const b=await r.json();if(!r.ok)throw Error(b.error?.message??"保存失败");setDraft({...value,revision:b.revision});setNotice("已保存商品配置草稿，需审核发布。");try{await onSaved();}catch{setNotice("保存成功，刷新失败，请手动刷新。");}
 }catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 return <section><h2>系统商店商品配置</h2><p>系统向玩家出售商品，只能购买，不支持玩家出售或回购。价格单位：灵石。当前为配置草稿，购买与刷新事务尚未接入。</p>
 <fieldset disabled={busy} className={styles.flatFieldset}><div className={styles.form}>{([['refreshSeconds','自然刷新间隔（秒）'],['randomSlots','随机栏格数'],['refreshBase','手动刷新基础费用'],['refreshPerMap','每增加一张地图的费用'],['currentTierPercent','当前档资源包概率（%）']] as const).map(([key,label])=><label key={key}>{label}<input type="number" value={value[key]} onChange={e=>setDraft({...value,[key]:Number(e.target.value)})}/></label>)}</div>
 <p>手动刷新费用 = 基础费用 + 每地图费用 ×（最高地图序号 − 1）；不改变自然刷新时间。资源包剩余概率取上一档；资源种类在已解锁岗位和钱包资源中等权抽取，未开放的庚精不进入池。随机商品库存按下方大类的上下限生成，上方库存为默认上限。</p>
 {(['fixed','random'] as const).map(shelf=><div key={shelf}><h3>{shelf==="fixed"?"常备商品":"随机商品"}</h3><div className={styles.scroll}><table><thead><tr><th>商品</th><th>价格</th><th>库存</th><th>开放地图</th><th>启用</th></tr></thead><tbody>{value.goods.map((g,i)=>g.shelf!==shelf?null:<tr key={g.code}><td>{data.items.find(item=>item.code===g.itemCode)?.name??g.itemCode}<code className={ui.code}>{g.itemCode}</code></td>{(['price','stock','minMap'] as const).map(key=><td key={key}>{key==="stock"&&shelf==="random"?<span>{value.groups.find(x=>x.code===g.groupCode)?.stockMin}–{value.groups.find(x=>x.code===g.groupCode)?.stockMax}</span>:<input aria-label={`${g.code} ${key}`} type="number" min={1} value={g[key]} onChange={e=>setDraft({...value,goods:value.goods.map((row,n)=>n===i?{...row,[key]:Number(e.target.value)}:row)})}/>}</td>)}<td><input aria-label={`${g.code} 启用`} type="checkbox" checked={g.enabled} onChange={e=>setDraft({...value,goods:value.goods.map((row,n)=>n===i?{...row,enabled:e.target.checked}:row)})}/></td></tr>)}</tbody></table></div></div>)}
 <h3>随机大类</h3><p>按已开放且已就绪的大类重新归一化权重。蓝图组已保存策划权重与价格，商品蓝图引用未齐备，保持待定。蓝图不重复，已永久解锁的蓝图移出随机池。</p><div className={styles.scroll}><table><thead><tr><th>大类</th><th>权重</th><th>最低地图</th><th>库存下限 / 上限</th><th>地图1–4价格</th><th>配置状态</th></tr></thead><tbody>{value.groups.map((g,i)=><tr key={g.code}><td>{g.name}</td>{(['weight','minMap'] as const).map(key=><td key={key}><input type="number" aria-label={`${g.name} ${key}`} value={g[key]} onChange={e=>setDraft({...value,groups:value.groups.map((row,n)=>n===i?{...row,[key]:Number(e.target.value)}:row)})}/></td>)}<td>{(['stockMin','stockMax'] as const).map(key=><input key={key} type="number" aria-label={`${g.name} ${key}`} value={g[key]} onChange={e=>setDraft({...value,groups:value.groups.map((row,n)=>n===i?{...row,[key]:Number(e.target.value)}:row)})}/>)}</td><td>{g.availability==="ready"?"按上方商品定价":g.prices.map((price,index)=><input key={index} type="number" aria-label={`${g.name} 地图${index+1}价格`} value={price} onChange={e=>setDraft({...value,groups:value.groups.map((row,n)=>n===i?{...row,prices:row.prices.map((p,x)=>x===index?Number(e.target.value):p)}:row)})}/>)}</td><td>{g.availability==="ready"?"已配置":"蓝图引用待补"}</td></tr>)}</tbody></table></div>
 <button disabled={busy} onClick={save}>{busy?"保存中…":"保存交易行配置"}</button></fieldset>{notice&&<p role="status">{notice}</p>}</section>;
}
